name: Corinthians Manual

on:
  workflow_dispatch:  # Manually trigger the workflow

jobs:
  run_python_script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Specify the Python version you want to use

    - name: Install dependencies
      run: pip install requests  # Instale as dependências necessárias

    - name: Run script
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: python Pythons.py  # Rode o script Python
